import os
DATABASE_NAME = "PhishingWebsitesInfo"
COLLECTION_NAME = "Phishing_collect"
ARTIFACT_DIR = "artifact"
DATA_INGESTION_DIR_NAME = "data_ingestion"
FEATURE_STORE_DIR_NAME = "feature_store"
TRAIN_TEST_SPLIT_RATIO = 0.2
TRAIN_FILE_NAME = "train.csv"
TEST_FILE_NAME = "test.csv"
FILE_NAME = "phishing_data.csv"
DATA_VALIDATION_DIR_NAME = "data_validation"
DATA_VALIDATION_STATUS_FILE = "status.txt"
SCHEMA_FILE_PATH = os.path.join("config", "schema.yaml")
DATA_TRANSFORMATION_DIR_NAME = "data_transformation"
DATA_TRANSFORMATION_TRANSFORMED_DATA_DIR = "transformed"
DATA_TRANSFORMATION_TRANSFORMED_OBJECT_DIR = "transformed_object"
TRANSFORMED_TRAIN_FILE_NAME = "train.npy"
TRANSFORMED_TEST_FILE_NAME = "test.npy"
PREPROCESSING_OBJECT_FILE_NAME = "preprocessing.pkl"
TARGET_COLUMN = "Result"
MODEL_TRAINER_DIR_NAME = "model_trainer"
MODEL_TRAINER_TRAINED_MODEL_DIR = "trained_model"
MODEL_TRAINER_TRAINED_MODEL_NAME = "model.pkl"
MODEL_TRAINER_EXPECTED_SCORE = 0.5
MODEL_CONFIG_FILE_PATH = os.path.join("config", "model.yaml")
PREDICTION_OUTPUT_DIR_NAME = "predictions"
PREDICTION_FILE_NAME = "predicted_file.csv"
PREDICTION_INPUT_DIR_NAME = "prediction_artifacts"
SAVED_MODEL_FILE_PATH = os.path.join("saved_models", "model.pkl")
HUGGINGFACE_REPO_ID = "TechDebugger/phishing-classifier-model"
HUGGINGFACE_MODELL_FILENAME = "model.pkl"